name = "adt"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.63.0 and < 1.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
bidict = ">= 1.0.0 and < 2.0.0"
bigdecimal = ">= 1.1.0 and < 2.0.0"
bitsandbobs = ">= 1.1.0 and < 2.0.0"
dijkstra = ">= 1.0.0 and < 2.0.0"
gleam_community_maths = ">= 2.0.0 and < 3.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gleamy_structures = ">= 1.2.0 and < 2.0.0"
glearray = ">= 2.1.0 and < 3.0.0"
ieee_float = ">= 1.5.0 and < 2.0.0"
iv = ">= 1.3.2 and < 2.0.0"
stdin = ">= 2.0.2 and < 3.0.0"
trie_again = ">= 1.1.3 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
